name: Discord

on: workflow_dispatch

jobs:
  discord:
    runs-on: ubuntu-slim
    steps:
      - name: Hello world action
        env: # Set the secret as an input
          discord_secret: ${{ secrets.Discord }}
          super_secret: ${{ secrets.Test }}
          super_var: ${{ vars.Test2 }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"$super_var"}' $discord_secret
