name: Intro

on: workflow_dispatch

jobs:
  say-hello:
    runs-on: ubuntu-slim
    steps:
      - name: Hello world action
        env: # Set the secret as an input
          super_secret: ${{ secrets.Test }}
        run: echo "$SUPER_SECRET"
